//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Above Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Above_Normal {
            get {
                return ResourceManager.GetString("String_Above_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_History {
            get {
                return ResourceManager.GetString("String_Backup_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Interval {
            get {
                return ResourceManager.GetString("String_Backup_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Now {
            get {
                return ResourceManager.GetString("String_Backup_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup process completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_process_completed {
            get {
                return ResourceManager.GetString("String_Backup_process_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup process failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_process_failed {
            get {
                return ResourceManager.GetString("String_Backup_process_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup process in progress. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_process_in_progress {
            get {
                return ResourceManager.GetString("String_Backup_process_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Source {
            get {
                return ResourceManager.GetString("String_Backup_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process was canceled because the backup target does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_target_does_not_exist {
            get {
                return ResourceManager.GetString("String_Backup_target_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Thread Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Thread_Priority {
            get {
                return ResourceManager.GetString("String_Backup_Thread_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Below Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Below_Normal {
            get {
                return ResourceManager.GetString("String_Below_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Completed {
            get {
                return ResourceManager.GetString("String_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Contains {
            get {
                return ResourceManager.GetString("String_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Failed {
            get {
                return ResourceManager.GetString("String_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileSpecific Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_File_Specific_Settings {
            get {
                return ResourceManager.GetString("String_File_Specific_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Free_Space {
            get {
                return ResourceManager.GetString("String_Free_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Highest {
            get {
                return ResourceManager.GetString("String_Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lowest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Lowest {
            get {
                return ResourceManager.GetString("String_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum Number of Backups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Maximum_Number_of_Backups {
            get {
                return ResourceManager.GetString("String_Maximum_Number_of_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Min {
            get {
                return ResourceManager.GetString("String_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Normal {
            get {
                return ResourceManager.GetString("String_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Off {
            get {
                return ResourceManager.GetString("String_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_On {
            get {
                return ResourceManager.GetString("String_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Source Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Open_Backup_Source_Folder {
            get {
                return ResourceManager.GetString("String_Open_Backup_Source_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Save Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Open_Save_Location {
            get {
                return ResourceManager.GetString("String_Open_Save_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Positive Integer Only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Positive_Integer_Only {
            get {
                return ResourceManager.GetString("String_Positive_Integer_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Processing {
            get {
                return ResourceManager.GetString("String_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Ready {
            get {
                return ResourceManager.GetString("String_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Save_Location {
            get {
                return ResourceManager.GetString("String_Save_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process was canceled because location where to save does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Save_location_does_not_exist {
            get {
                return ResourceManager.GetString("String_Save_location_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scheduled Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Scheduled_Backup {
            get {
                return ResourceManager.GetString("String_Scheduled_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to be backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Select_Backup_Folder {
            get {
                return ResourceManager.GetString("String_Select_Backup_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a location where to save the backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Select_Save_Location {
            get {
                return ResourceManager.GetString("String_Select_Save_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Size {
            get {
                return ResourceManager.GetString("String_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringFormat_Files {
            get {
                return ResourceManager.GetString("StringFormat_Files", resourceCulture);
            }
        }
    }
}
