//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatString_Files {
            get {
                return ResourceManager.GetString("FormatString_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Above Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Above_Normal {
            get {
                return ResourceManager.GetString("String_Above_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_App_Settings {
            get {
                return ResourceManager.GetString("String_App_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App startup and resident mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_App_Startup_Mode {
            get {
                return ResourceManager.GetString("String_App_Startup_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_History {
            get {
                return ResourceManager.GetString("String_Backup_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Interval {
            get {
                return ResourceManager.GetString("String_Backup_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Now {
            get {
                return ResourceManager.GetString("String_Backup_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup process completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_process_completed {
            get {
                return ResourceManager.GetString("String_Backup_process_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup process failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_process_failed {
            get {
                return ResourceManager.GetString("String_Backup_process_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup process in progress. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_process_in_progress {
            get {
                return ResourceManager.GetString("String_Backup_process_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Settings {
            get {
                return ResourceManager.GetString("String_Backup_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Source {
            get {
                return ResourceManager.GetString("String_Backup_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process was canceled because the backup target does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_target_does_not_exist {
            get {
                return ResourceManager.GetString("String_Backup_target_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm when backup target is very large に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Target_Size_Confirm {
            get {
                return ResourceManager.GetString("String_Backup_Target_Size_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The backup task canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Task_Canceled {
            get {
                return ResourceManager.GetString("String_Backup_Task_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup Thread Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Backup_Thread_Priority {
            get {
                return ResourceManager.GetString("String_Backup_Thread_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Below Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Below_Normal {
            get {
                return ResourceManager.GetString("String_Below_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Check_All {
            get {
                return ResourceManager.GetString("String_Check_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Completed {
            get {
                return ResourceManager.GetString("String_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Confirm {
            get {
                return ResourceManager.GetString("String_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Contains {
            get {
                return ResourceManager.GetString("String_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Do_You_Want_To_Continue {
            get {
                return ResourceManager.GetString("String_Do_You_Want_To_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Failed {
            get {
                return ResourceManager.GetString("String_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileSpecific Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_File_Specific_Settings {
            get {
                return ResourceManager.GetString("String_File_Specific_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Free_Space {
            get {
                return ResourceManager.GetString("String_Free_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The backup target is larger than the available free space on the destination storage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Free_Space_Check {
            get {
                return ResourceManager.GetString("String_Free_Space_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Highest {
            get {
                return ResourceManager.GetString("String_Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Language {
            get {
                return ResourceManager.GetString("String_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lowest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Lowest {
            get {
                return ResourceManager.GetString("String_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum Number of Backups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Maximum_Number_of_Backups {
            get {
                return ResourceManager.GetString("String_Maximum_Number_of_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Min {
            get {
                return ResourceManager.GetString("String_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Normal {
            get {
                return ResourceManager.GetString("String_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Off {
            get {
                return ResourceManager.GetString("String_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_On {
            get {
                return ResourceManager.GetString("String_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the source folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Open_Backup_Source_Folder {
            get {
                return ResourceManager.GetString("String_Open_Backup_Source_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the destination to save to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Open_Save_Location {
            get {
                return ResourceManager.GetString("String_Open_Save_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Positive integer only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Positive_Integer_Only {
            get {
                return ResourceManager.GetString("String_Positive_Integer_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Positive Number Only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Positive_Number_Only {
            get {
                return ResourceManager.GetString("String_Positive_Number_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Processing {
            get {
                return ResourceManager.GetString("String_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Ready {
            get {
                return ResourceManager.GetString("String_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Refresh {
            get {
                return ResourceManager.GetString("String_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Save_Location {
            get {
                return ResourceManager.GetString("String_Save_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process was canceled because the storage location does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Save_location_does_not_exist {
            get {
                return ResourceManager.GetString("String_Save_location_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scheduled Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Scheduled_Backup {
            get {
                return ResourceManager.GetString("String_Scheduled_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to be backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Select_Backup_Folder {
            get {
                return ResourceManager.GetString("String_Select_Backup_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a location where to save the backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Select_Save_Location {
            get {
                return ResourceManager.GetString("String_Select_Save_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Settings {
            get {
                return ResourceManager.GetString("String_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show window and tray icon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Show_Window_And_TrayIcon {
            get {
                return ResourceManager.GetString("String_Show_Window_And_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show window without tray icon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Show_Window_Only {
            get {
                return ResourceManager.GetString("String_Show_Window_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Size {
            get {
                return ResourceManager.GetString("String_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Target_Size {
            get {
                return ResourceManager.GetString("String_Target_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The backup target size is very large. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Target_Size_Very_Large {
            get {
                return ResourceManager.GetString("String_Target_Size_Very_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray icon only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Tray_Icon_Only {
            get {
                return ResourceManager.GetString("String_Tray_Icon_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uncheck all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Uncheck_All {
            get {
                return ResourceManager.GetString("String_Uncheck_All", resourceCulture);
            }
        }
    }
}
